import { Component, OnInit } from '@angular/core';
import { IonList, IonItem, IonLabel, IonButton } from "@ionic/angular/standalone";
import { FirebaseService } from 'src/services/firebase.service';

@Component({
  selector: 'app-firestore',
  standalone: true,
  imports: [IonList, IonItem, IonLabel, IonButton],
  templateUrl: './firestore.component.html',
  styleUrls: ['./firestore.component.scss'],
})
export class FirestoreComponent implements OnInit {

  constructor(private firestore: FirebaseService) { }

  ngOnInit() { }

  addProduct() {
    const listProducts = [
      // -- Switch --
      { "name": "Switch - 5A" },
      { "name": "Switch - 15A" },
      { "name": "Switch - 20A" },
      { "name": "Switch - 2Way" },
      { "name": "Switch Dummy" },
      { "name": "Switch Bell" },
      { "name": "DP Switch - 32A" },
      { "name": "Indicator" },
      { "name": "USB Socket" },
      { "name": "Socket - 2pin" },
      { "name": "Socket - 16A" },
      { "name": "Socket - 5A" },
      { "name": "Fan Dimmer" },
      { "name": "Fuse carrier - 16/415A" },
      { "name": "Fuse carrier - 32/415A" },
      { "name": "Tape Roll" },

      // -- Wall Fitting --
      { "name": "Ceiling Rose" },
      { "name": "Angle Holder" },
      { "name": "Batten Holder" },
      { "name": "Pendent Holder" },
      { "name": "2 Pin Top" },
      { "name": "3 Pin Top" },
      { "name": "Round Sheet" },
      { "name": "Round Sheet Dummy" },
      { "name": "Fan Round Sheet" },
      { "name": "Calling Bell" },

      // -- Board --
      { "name": "Wood Board - 15*4" },
      { "name": "Wood Board - 12*6" },
      { "name": "Wood Board - 12*4" },
      { "name": "Wood Board - 10*6" },
      { "name": "Wood Board - 10*4" },
      { "name": "Wood Board - 8*6" },
      { "name": "Wood Board - 8*4" },
      { "name": "Wood Board - 6*4" },
      { "name": "Wood Board - 4*4" },
      { "name": "Metal Box - 2M" },
      { "name": "Metal Box - 3M" },
      { "name": "Metal Box - 4M" },
      { "name": "Metal Box - 6M" },
      { "name": "Metal Box - 8M" },
      { "name": "Metal Box - 10M" },
      { "name": "Metal Box - 12M" },
      { "name": "Metal Box - 16M" },
      { "name": "Meter Board - 12*9" },
      { "name": "Meter Board - 15*12" },
      { "name": "Meter Board - 24*18" },
      { "name": "T Bolt" },
      { "name": "Earth Link - Copper" },
      { "name": "Stay Clamp - 3/4\"" },
      { "name": "Stay Clamp - 1\"" },
      { "name": "Service Pipe -3/4\"" },
      { "name": "Service Pipe - 1\"" },

      // -- Board Sheets --
      { "name": "Wood Model Sheet - 12*4" },
      { "name": "Wood Model Sheet - 10*6" },
      { "name": "Wood Model Sheet - 10*4" },
      { "name": "Wood Model Sheet - 8*4" },
      { "name": "Wood Model Sheet - 6*4" },
      { "name": "Wood Model Sheet - 4*4" },
      { "name": "Metal Box Sheet - 2M" },
      { "name": "Metal Box Sheet - 3M" },
      { "name": "Metal Box Sheet - 4M" },
      { "name": "Metal Box Sheet - 6M" },
      { "name": "Metal Box Sheet - 8M" },
      { "name": "Metal Box Sheet - 12M" },
      { "name": "Metal Box Sheet - 16M" },

      // -- Pipes Fitting --
      { "name": "Junction Box - 1W" },
      { "name": "Junction Box - 2W" },
      { "name": "Junction Box - 3W" },
      { "name": "Junction Box - 4W" },
      { "name": "Depth Box - 3/4\"" },
      { "name": "Depth Box - 1\"" },
      { "name": "Bend - 3/4\"" },
      { "name": "Bend - 1\"" },
      { "name": "pipe 3/4 - 2MM" },
      { "name": "pipe 3/4 - 1.5MM" },
      { "name": "Pipe 1\" - 2MM" },
      { "name": "Pipe 1\" - 1.5MM" },
      { "name": "Fan Box - Metal" },
      { "name": "Fan Box - PVC" },
      { "name": "Spot Light Box" },

      // -- Trip --
      { "name": "MCB - 10A" },
      { "name": "MCB - 16A" },
      { "name": "MCB - 20A" },
      { "name": "MCB Two pol- 32A" },
      { "name": "MCB Two pol- 40A" },
      { "name": "MCB Box - 2Pol" },
      { "name": "MCB Box - 3Pol" },
      { "name": "MCB Box - 4Pol" },
      { "name": "ELCB - 10A" },
      { "name": "ELCB - 16A" },
      { "name": "ELCB - 20A" },
      { "name": "ELCB Two pol - 32A" },
      { "name": "ELCB Two pol - 40A" },
      { "name": "Isolator Two Pol - 32A" },
      { "name": "Isolator Two Pol - 40A" },
      { "name": "Isolator Four Pol - 32A" },
      { "name": "Isolator Four Pol - 40A" },
      { "name": "RCCB Two Pol - 32A" },
      { "name": "RCCB Two Pol - 40A" },
      { "name": "Panel Box - 6M" },
      { "name": "Panel Box - 8M" },
      { "name": "Panel Box - 12M" },
      { "name": "3 Phase Panel Board - 16M" },
      { "name": "3 Phase Panel Board - 18M" },
      { "name": "Rotary Switch - 63A" },

      // -- Lights --
      { "name": "Tube Light LED" },
      { "name": "LED Bulb - 9W" },
      { "name": "LED Bulb - 12W" },
      { "name": "LED Bulb - 23W" },
      { "name": "LED Bulkhead - 12W" },
      { "name": "LED Bulkhead - 18W" },
      { "name": "LED Bulkhead - 20W" },
      { "name": "LED Bulkhead - 23W" },
      { "name": "Spot light - W" },
      { "name": "Spot light - WW" },
      { "name": "Spot light - MC" },
      { "name": "Spot light - B" },
      { "name": "Spot light - G" },
      { "name": "Spot light - P" },
      { "name": "Stair Light" },
      { "name": "Slip Light - W" },
      { "name": "Slip Light - WW" },
      { "name": "Slip Light - MC" },
      { "name": "Slip Light - B" },
      { "name": "Slip Light - G" },
      { "name": "Slip Light - v" },
      { "name": "Foot lamb Light - 4 Model" },
      { "name": "Foot lamb Light - 3Model" },
      { "name": "Gate Light" },
      { "name": "Depth Box Light - W" },
      { "name": "Depth Box Light - WW" },
      { "name": "Depth Box Light - MC" },
      { "name": "Depth Box Light - B" },
      { "name": "Depth Box Light - G" },
      { "name": "Depth Box Light - P" },

      // -- Wire --
      { "name": "Wire - 1 QMM" },
      { "name": "Wire - 1.5-QMM" },
      { "name": "Wire - 2.5-QMM" },
      { "name": "Wire - 4-QMM" },
      { "name": "Speaker Wire" },
      { "name": "CTS Wire - 3/20" },
      { "name": "CTS Wire - 7/20" },
      { "name": "Reel - 2P" },
      { "name": "Reel - 4P" },
      { "name": "Green Wire - 1/2Kg" },
      { "name": "Green Wire - 1kg" },
      { "name": "Green Wire - 2kg" },

      // -- Sintex Tank --
      { "name": "Tank - 500L - 3L" },
      { "name": "Tank - 500L - 4L" },
      { "name": "Tank - 750L - 3L" },
      { "name": "Tank - 750L - 4L" },
      { "name": "Tank - 1000L - 3L" },
      { "name": "Tank - 1000L - 4L" },

      // -- Valve --
      { "name": "Ball Valve Brass - 1/2\"" },
      { "name": "Ball Valve Brass - 3/4\"" },
      { "name": "Ball Valve Brass - 1\"" },
      { "name": "Ball Valve Brass - 1/4\"" },
      { "name": "Ball Valve Brass - 1/2\"" },
      { "name": "Angle Valve" },
      { "name": "NRV Valve - 3/4\"" },
      { "name": "NRV Valve - 1\"" },
      { "name": "NRV Valve - 1/4\"" },
      { "name": "NRV Valve - 1/2\"" },
      { "name": "NRV Valve - 2\"" },

      // -- Tap --
      { "name": "CP Tap" },
      { "name": "PVC Tap" },
      { "name": "Kitchen Tap" },
      { "name": "Wash basin Tap" },
      { "name": "Washing Machine Tap" },

      // -- Solvent --
      { "name": "Solvent - 50ML" },
      { "name": "Solvent - 100ML" },
      { "name": "Solvent CPVC - 50ML" },
      { "name": "Solvent CPVC - 100ML" },
      { "name": "Pull Tag" },

      // -- UPVC --
      { "name": "Tank Connector UPVC - 3/4\"" },
      { "name": "Tank Connector UPVC - 1\"" },
      { "name": "Tank Connector UPVC - 1-1/4\"" },
      { "name": "Tee UPVC - 1/2\"" },
      { "name": "Tee UPVC - 3/4\"" },
      { "name": "Tee UPVC - 1\"" },
      { "name": "Tee UPVC - 1-1/4\"" },
      { "name": "Tee UPVC - 1-1/2\"" },
      { "name": "Coupler UPVC - 1/2\"" },
      { "name": "Coupler UPVC - 3/4\"" },
      { "name": "Coupler UPVC - 1\"" },
      { "name": "Coupler UPVC - 1-1/4\"" },
      { "name": "Coupler UPVC - 1-1/2\"" },
      { "name": "Elbow UPVC - 1/2\"" },
      { "name": "Elbow UPVC - 3/4\"" },
      { "name": "Elbow UPVC - 1\"" },
      { "name": "Elbow UPVC - 1-1/4\"" },
      { "name": "Elbow UPVC - 1-1/2\"" },
      { "name": "MTA UPVC - 1/2\"" },
      { "name": "MTA UPVC - 3/4\"" },
      { "name": "MTA UPVC - 1\"" },
      { "name": "MTA UPVC - 1-1/4\"" },
      { "name": "MTA UPVC - 1-1/2\"" },
      { "name": "FTA UPVC - 1/2\"" },
      { "name": "FTA UPVC - 3/4\"" },
      { "name": "FTA UPVC - 1\"" },
      { "name": "FTA UPVC - 1-1/4\"" },
      { "name": "FTA UPVC - 1-1/2\"" },
      { "name": "Union UPVC - 1/2\"" },
      { "name": "Union UPVC - 3/4\"" },
      { "name": "Union UPVC - 1\"" },
      { "name": "Union UPVC - 1-1/4\"" },
      { "name": "Union UPVC - 1-1/2\"" },
      { "name": "Brass Reducer UPVC - 3/4*1/2" },
      { "name": "Brass Elbow UPVC - 3/4*1/2" },
      { "name": "Brass Tee UPVC - 3/4*1/2" },
      { "name": "Reducing Tee UPVC - 1*3/4" },

      // -- CPVC Fitting --
      { "name": "Tank Connector CPVC - 3/4\"" },
      { "name": "Tank Connector CPVC - 1\"" },
      { "name": "Tank Connector CPVC - 1-1/4\"" },
      { "name": "Tee CPVC - 1/2\"" },
      { "name": "Tee CPVC - 3/4\"" },
      { "name": "Tee CPVC - 1\"" },
      { "name": "Tee CPVC - 1-1/4\"" },
      { "name": "Tee CPVC - 1-1/2\"" },
      { "name": "Coupler CPVC - 1/2\"" },
      { "name": "Coupler CPVC - 3/4\"" },
      { "name": "Coupler CPVC - 1\"" },
      { "name": "Coupler CPVC - 1-1/4\"" },
      { "name": "Coupler CPVC - 1-1/2\"" },
      { "name": "Elbow CPVC - 1/2\"" },
      { "name": "Elbow CPVC - 3/4\"" },
      { "name": "Elbow CPVC - 1\"" },
      { "name": "Elbow CPVC - 1-1/4\"" },
      { "name": "Elbow CPVC - 1-1/2\"" },
      { "name": "MTA CPVC - 1/2\"" },
      { "name": "MTA CPVC - 3/4\"" },
      { "name": "MTA CPVC - 1\"" },
      { "name": "MTA CPVC - 1-1/4\"" },
      { "name": "MTA CPVC - 1-1/2\"" },
      { "name": "FTA CPVC - 1/2\"" },
      { "name": "FTA CPVC - 3/4\"" },
      { "name": "FTA CPVC - 1\"" },
      { "name": "FTA CPVC - 1-1/4\"" },
      { "name": "FTA CPVC - 1-1/2" },
      { "name": "Union CPVC - 1/2\"" },
      { "name": "Union CPVC - 3/4\"" },
      { "name": "Union CPVC - 1\"" },
      { "name": "Union CPVC - 1-1/4\"" },
      { "name": "Union CPVC - 1-1/2\"" },
      { "name": "Brass Reducer CPVC - 3/4*1/2" },
      { "name": "Brass Elbow CPVC - 3/4*1/2" },
      { "name": "Brass Tee CPVC - 3/4*1/2" },
      { "name": "Reducing Tee CPVC - 1*3/4" },

      // -- PVC_Fittings --
      { "name": "FTA PVC - 1/2\"" },
      { "name": "FTA PVC - 3/4\"" },
      { "name": "FTA PVC - 1\"" },
      { "name": "FTA PVC - 1-1/4\"" },
      { "name": "FTA PVC - 1-1/2\"" },
      { "name": "MTA PVC - 1/2\"" },
      { "name": "MTA PVC - 3/4\"" },
      { "name": "MTA PVC - 1\"" },
      { "name": "MTA PVC - 1-1/4\"" },
      { "name": "MTA PVC - 1-1/2\"" },
      { "name": "Elbow PVC - 1/2\"" },
      { "name": "Elbow PVC - 3/4\"" },
      { "name": "Elbow PVC - 1\"" },
      { "name": "Elbow PVC - 1-1/4\"" },
      { "name": "Elbow PVC - 1-1/2\"" },
      { "name": "Elbow PVC - 2\"" },
      { "name": "Elbow PVC - 2-1/2\"" },
      { "name": "Elbow PVC - 3\"" },
      { "name": "Elbow PVC - 4\"" },
      { "name": "Reducer PVC - 1*3/4\"" },
      { "name": "Reducer PVC - 1-1/4*1" },
      { "name": "Tee PVC - 1/2\"" },
      { "name": "Tee PVC - 3/4\"" },
      { "name": "Tee PVC - 1\"" },
      { "name": "Tee PVC - 1-1/4\"" },
      { "name": "Tee PVC - 1-1/2\"" },
      { "name": "Tee PVC - 2\"" },
      { "name": "Tee PVC - 2-1/2\"" },
      { "name": "Tee PVC - 3\"" },
      { "name": "Tee PVC - 4\"" },
      { "name": "End Cup PVC - 1/2\"" },
      { "name": "End Cup PVC - 3/4\"" },
      { "name": "End Cup PVC - 1\"" },
      { "name": "End Cup PVC - 1-1/4\"" },
      { "name": "End Cup PVC - 1-1/2\"" },
      { "name": "End Cup PVC - 2\"" },
      { "name": "End Cup PVC - 2-1/2\"" },
      { "name": "End Cup PVC - 3\"" },
      { "name": "End Cup PVC - 4\"" },
      { "name": "Clip PVC - 1/2\"" },
      { "name": "Clip PVC - 3/4\"" },
      { "name": "Clip PVC - 1\"" },
      { "name": "Clip PVC - 1-1/4\"" },
      { "name": "Clip PVC - 1-1/2\"" },
      { "name": "Clip PVC - 2\"" },
      { "name": "Clip PVC - 2-1/2\"" },
      { "name": "Clip PVC - 3\"" },
      { "name": "Clip PVC - 4\"" },
      { "name": "ST Pipes PVC - 1/2\"" },
      { "name": "ST Pipes PVC - 3/4\"" },
      { "name": "ST Pipes PVC - 1\"" },
      { "name": "ST Pipes PVC - 1-1/4\"" },
      { "name": "ST Pipes PVC - 1-1/2\"" },
      { "name": "ST Pipes PVC - 2\"" },
      { "name": "ST Pipes PVC - 2-1/2\"" },
      { "name": "ST Pipes PVC - 3\"" },
      { "name": "ST Pipes PVC - 4\"" },
      { "name": "Bypass Bend PVC - 1\"" },
      { "name": "Bypass Bend PVC - 3/4\"" },
      { "name": "Coupler PVC - 1/2\"" },
      { "name": "Coupler PVC - 3/4\"" },
      { "name": "Coupler PVC - 1\"" },
      { "name": "Coupler PVC - 1-1/4\"" },
      { "name": "Coupler PVC - 1-1/2\"" },
      { "name": "Coupler PVC - 2\"" },
      { "name": "Coupler PVC - 2-1/2\"" },
      { "name": "Coupler PVC - 3\"" },
      { "name": "Coupler PVC - 4\"" },
      { "name": "Union PVC - 1/2\"" },
      { "name": "Union PVC - 3/4\"" },
      { "name": "Union PVC - 1\"" },
      { "name": "Union PVC - 1-1/4\"" },
      { "name": "Union PVC - 1-1/2\"" },
      { "name": "Door Elbow PVC - 1-1/2\"" },
      { "name": "Door Elbow PVC - 2\"" },
      { "name": "Door Elbow PVC - 2-1/2\"" },
      { "name": "Door Elbow PVC - 3\"" },
      { "name": "Door Elbow PVC - 4\"" },
      { "name": "Door Tee PVC - 1-1/2\"" },
      { "name": "Door Tee PVC - 2\"" },
      { "name": "Door Tee PVC - 2-1/2\"" },
      { "name": "Door Tee PVC - 3\"" },
      { "name": "Door Tee PVC - 4\"" },
      { "name": "Door Y PVC - 2\"" },
      { "name": "Door Y PVC - 2-1/2\"" },
      { "name": "Door Y PVC - 3\"" },
      { "name": "Door Y PVC - 4\"" },
      { "name": "Y PVC - 2\"" },
      { "name": "Y PVC - 2-1/2\"" },
      { "name": "Y PVC - 3\"" },
      { "name": "Y PVC - 4\"" },
      { "name": "Bend PVC - 1/2\"" },
      { "name": "Bend PVC - 3/4\"" },
      { "name": "Bend PVC - 1\"" },
      { "name": "Bend PVC - 1-1/4\"" },
      { "name": "Bend PVC - 1-1/2\"" },
      { "name": "Bend PVC - 2\"" },
      { "name": "Bend PVC - 2-1/2\"" },
      { "name": "Bend PVC - 3\"" },
      { "name": "Bend PVC - 4\"" },
      { "name": "Step Clamp - 1-1/2\"" },
      { "name": "Step Clamp - 2\"" },
      { "name": "Step Clamp - 2-1/2\"" },
      { "name": "Step Clamp - 3\"" },
      { "name": "Step Clamp - 4\"" },
      { "name": "Thread" },
      { "name": "Teflon Tread Tape" },
      { "name": "SS (Nail)Aani - 1*1/2\"" },
      { "name": "SS (Nail)Aani - 2\"" },

      // -- Compressor Motor --
      { "name": "Hp Compressor Motor - 1-1/2" },
      { "name": "Hose Meter - 1/2\"" },
      { "name": "Hose Meter - 1\"" },
      { "name": "Clip - 1/2\"" },
      { "name": "Clip - 1\"" },
      { "name": "Bottom Unit" },
      { "name": "Hose Collar - 1/2\"" },
      { "name": "Hose Collar - 3/4\"" },
      { "name": "Hose Collar - 1\"" },
      { "name": "GI Pipe - 1/2\"" },
      { "name": "Gi Elbow - 1/2\"" },
      { "name": "Gi Elbow - 1-3/4\"" },
      { "name": "Gi Coupling - 1/2\"" },
      { "name": "Gi Coupling - 1\"" },
      { "name": "MS Union - 1/2\"" },
      { "name": "Pipe Nipple - (1/2 x 24)" },
      { "name": "Pipe Nipple - (1/2 x 18)" },
      { "name": "Pipe Nipple - (1/2 x 12)" },
      { "name": "Pipe Nipple - (1/2 x 6)" },
      { "name": "Pipe Nipple - (1 x 9)" },
      { "name": "Nipple - 1/2\"" },
      { "name": "Clamp - (1-1/2)" },
      { "name": "Bore well Cap - (7\")" },
      { "name": "Oil - (1/2-Lt)" }
    ]
    listProducts.forEach(async (product: any) => {
      const uploadId = this.firestore.createId();
      // await this.firestore.set(`listProducts/${uploadId}`, {
      //   name: product?.name
      // })
      console.log("done")
    })
  }

}
